system:
  helloworld:
    container: !system/component
      system/component-kind: testcontainers/container
      docker-image-name: testcontainers/helloworld:1.1.0
      exposed-ports:
        - 8080
        - 8081

    container-mapped-exposed-port: !system/component
      system/component-kind: testcontainers/container-mapped-exposed-port
      container: !system/local-ref container
      exposed-port: 8080

    container-mapped-ports: !system/component
      system/component-kind: testcontainers/container-mapped-ports
      container: !system/local-ref container
